#!/usr/bin/env bash                                                                                                                                                                                                                                                            


sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /groups/ameres/Pooja/Projects/zebrafishAnnotation/sequencingRun_december2017/analysis/annotation/stageSpecific/dataForAnnotation/stageSpecificAnnotation/TP1/ -o /scratch/pooja/SLAMannotation/dr/TP1/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m p -c TP1_new

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /groups/ameres/Pooja/Projects/zebrafishAnnotation/sequencingRun_december2017/analysis/annotation/stageSpecific/dataForAnnotation/stageSpecificAnnotation//TP2/ -o /scratch/pooja/SLAMannotation/dr/TP2/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m p -c TP2_new


sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /groups/ameres/Pooja/Projects/zebrafishAnnotation/sequencingRun_december2017/analysis/annotation/stageSpecific/dataForAnnotation/stageSpecificAnnotation//TP3/ -o /scratch/pooja/SLAMannotation/dr/TP3/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m p -c TP3_new


sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /groups/ameres/Pooja/Projects/zebrafishAnnotation/sequencingRun_december2017/analysis/annotation/stageSpecific/dataForAnnotation/stageSpecificAnnotation//TP4/ -o /scratch/pooja/SLAMannotation/dr/TP4/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m p -c TP4_new

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /groups/ameres/Pooja/Projects/zebrafishAnnotation/sequencingRun_december2017/analysis/annotation/stageSpecific/dataForAnnotation/stageSpecificAnnotation//TP5/ -o /scratch/pooja/SLAMannotation/dr/TP5/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m p -c TP5_new


sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /groups/ameres/Pooja/Projects/zebrafishAnnotation/sequencingRun_december2017/analysis/annotation/stageSpecific/dataForAnnotation/stageSpecificAnnotation//TP6/ -o /scratch/pooja/SLAMannotation/dr/TP6/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m p -c TP6_new


sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /groups/ameres/Pooja/Projects/zebrafishAnnotation/sequencingRun_december2017/analysis/annotation/stageSpecific/dataForAnnotation/stageSpecificAnnotation//TP7/ -o /scratch/pooja/SLAMannotation/dr/TP7/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m p -c TP7_new


sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /groups/ameres/Pooja/Projects/zebrafishAnnotation/sequencingRun_december2017/analysis/annotation/stageSpecific/dataForAnnotation/stageSpecificAnnotation//TP8/ -o /scratch/pooja/SLAMannotation/dr/TP8/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m p -c TP8_new


sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /groups/ameres/Pooja/Projects/zebrafishAnnotation/sequencingRun_december2017/analysis/annotation/stageSpecific/dataForAnnotation/stageSpecificAnnotation//TP9/ -o /scratch/pooja/SLAMannotation/dr/TP9/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m p -c TP9_new



