#!/usr/bin/env bash

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/Ski7_EPE_T1/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/Ski7_EPE_T1_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m p -c Ski7_EPE_T1_new

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/Ski7_EPE_T2/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/Ski7_EPE_T2_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m p -c Ski7_Emb_T2_new

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/Ski7_EPE_T3/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/Ski7_EPE_T3_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m p -c Ski7_Emb_T3_new

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/Ski7_EPE_T4/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/Ski7_EPE_T4_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m p -c Ski7_Emb_T4_new


sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/Ski7_Ooc_ACT/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/Ski7_Ooc_ACT_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m S -c Ski7_Ooc_ACT_new
sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/Ski7_Ooc_SQU/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/Ski7_Ooc_SQU_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m S -c Ski7_Ooc_SQU_new

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/Ski7_Ooc_FER/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/Ski7_Ooc_FER_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m S -c Ski7_Ooc_FER_new

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/Ski7_Ooc_T1/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/Ski7_Ooc_T1_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m S -c Ski7_Ooc_T1_new

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/Ski7_Ooc_T2/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/Ski7_Ooc_T2_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m S -c Ski7_Ooc_T2_new

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/Ski7_Ooc_T3/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/Ski7_Ooc_T3_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m S -c Ski7_Ooc_T3_new

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/Ski7_Ooc_T4/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/Ski7_Ooc_T4_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m S -c Ski7_Ooc_T4_new



## wt

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/WT_EPE_T1/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/WT_EPE_T1_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m p -c WT_Emb_T1_new

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/WT_EPE_T2/ -o /scratch/pooja/SLAMannotation/dr/quio_jan17//WT_EPE_T2_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m p -c WT_Emb_T2_new

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/WT_EPE_T3/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/WT_EPE_T3_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m p -c WT_Emb_T3_new

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/WT_EPE_T4/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/WT_EPE_T4_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m p -c WT_Emb_T4_new

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/WT_Ooc_ACT/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/WT_Ooc_ACT_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m S -c WT_Ooc_ACT_new
sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/WT_Ooc_SQU/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/WT_Ooc_SQU_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m S -c WT_Ooc_SQU_new

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/WT_Ooc_FER/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/WT_Ooc_FER_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m S -c WT_Ooc_FER_new

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/WT_Ooc_T1/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/WT_Ooc_T1_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m S -c WT_Ooc_T1_new

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/WT_Ooc_T2/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/WT_Ooc_T2_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m S -c WT_Ooc_T2_new

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/WT_Ooc_T3/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/WT_Ooc_T3_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m S -c WT_Ooc_T3_new

sbatch /groups/ameres/Pooja/Projects/refiningPipeline/pipeline/pre-processing/beforeMapping.new.sh -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG -i /scratch/pooja/inputQuio_new/WT_Ooc_T4/ -o /scratch/pooja/SLAMannotation/dr//quio_jan17/WT_Ooc_T4_new/ -g /groups/ameres/bioinformatics/references/danio_rerio/dr11/danRer11.fa -t 2 -u /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/refSeq_dr11_GRCz11_2019Sep20/ -e /groups/ameres/Pooja/Projects/zebrafishAnnotation/dr11/ensembl_dr11_Ensembl_Genes_93/ -m S -c WT_Ooc_T4_new

